// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxcTZUmcXjk38b1orQq6Urljzr-lGXAFM',
    appId: '1:533096001323:web:bb3f3eb772fc53110d1f6e',
    messagingSenderId: '533096001323',
    projectId: 'tutoring-app---auth',
    authDomain: 'tutoring-app---auth.firebaseapp.com',
    storageBucket: 'tutoring-app---auth.appspot.com',
    measurementId: 'G-EFY786HTLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfAqQz9lfXFqikUDSOuJnt_W2wGKAb0Y',
    appId: '1:533096001323:android:ddd55ac6b9e6c5a60d1f6e',
    messagingSenderId: '533096001323',
    projectId: 'tutoring-app---auth',
    storageBucket: 'tutoring-app---auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNb9Q0nkWJLHIhnGFxpcrsyFHl3yM-QQ',
    appId: '1:533096001323:ios:32d90711a10db8980d1f6e',
    messagingSenderId: '533096001323',
    projectId: 'tutoring-app---auth',
    storageBucket: 'tutoring-app---auth.appspot.com',
    iosBundleId: 'com.example.tutoringappAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoNb9Q0nkWJLHIhnGFxpcrsyFHl3yM-QQ',
    appId: '1:533096001323:ios:61961c1831abdfd20d1f6e',
    messagingSenderId: '533096001323',
    projectId: 'tutoring-app---auth',
    storageBucket: 'tutoring-app---auth.appspot.com',
    iosBundleId: 'com.example.tutoringappAuth.RunnerTests',
  );
}
